name: Required Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  labels-check:
    runs-on: ubuntu-latest
    steps:
      - uses: hudl/platform-actions/required-labels-check@latest
